services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./api:/srv/api  # 将宿主机的 api 目录挂载到容器内的 /srv/api
    networks:
      - network1
    command: |
      caddy run --config /etc/caddy/Caddyfile

    # 使用 Caddyfile 配置
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  network1:
    external: true

configs:
  caddyfile:
    file: ./Caddyfile  # 假设 Caddyfile 文件在当前目录下
